routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdvertiseCostController;
use App\Http\Controllers\BannerSizeController;
use App\Http\Controllers\BudgetProvisionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\FinancialYearController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\NewsPaperController;
use App\Http\Controllers\NewsPaperTypeController;
use App\Http\Controllers\PrintTypeController;
use App\Http\Controllers\PublicationTypeController;
use App\Http\Controllers\SignatureController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [LoginController::class, 'login'])->name('admin.login');

Route::group(['middleware' => ['auth']], function() {

    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

    Route::resource('advertise-cost', AdvertiseCostController::class);

    Route::resource('banner-size', BannerSizeController::class);

    Route::resource('budget-provision', BudgetProvisionController::class);

    Route::resource('department', DepartmentController::class);

    Route::resource('financial-year', FinancialYearController::class);

    Route::resource('language', LanguageController::class);

    Route::resource('news-paper', NewsPaperController::class);

    Route::resource('news-paper-type', NewsPaperTypeController::class);

    Route::resource('print-type', PrintTypeController::class);

    Route::resource('publication-type', PublicationTypeController::class);

    Route::resource('signature', SignatureController::class);
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\DepartmentRequest;
use App\Repository\Master\DepartmentRepository;

class DepartmentController extends Controller
{
    protected $departmentRepository;

    public function __construct(DepartmentRepository $departmentRepository){
        $this->departmentRepository = $departmentRepository;
    }

    public function index(){
        $departments = $this->departmentRepository->index();

        return view('master.department.index')->with([
            'departments' => $departments
        ]);
    }

    public function create(){
        return view('master.department.create');
    }

    public function store(DepartmentRequest $request){
        $department = $this->departmentRepository->store($request);

        if($department){
            return redirect()->route('department.index')->with('success', 'Department Created Successfully');
        }
    }

    public function edit($id){
        $department = $this->departmentRepository->store($id);

        return view('master.department.update')->with([
            'department' => $department
        ]);
    }

    public function update(DepartmentRequest $request){
        $department = $this->departmentRepository->update($request);

        if($department){
            return redirect()->route('department.index')->with('success', 'Department Updated Successfully');
        }
    }

    public function destroy(Request $request){
        $department = $this->departmentRepository->destroy($request);

        if($department){
            return redirect()->route('department.index')->with('success', 'Department Removed Successfully');
        }
    }
}

resources/views/master/department/create.blade.php
<x-layout>
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Department</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{ route('dashboard') }}">
                                <i data-feather="home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"> Department</li>
                        <li class="breadcrumb-item active"> List</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <form action="{{ route('department.store') }}" method="post">
                    @csrf
                    <div class="card">
                        <div class="card-header border-bottom pb-2">
                            <h5>Department</h5>
                        </div>
                        <div class="card-body">

                            <div class="row g-3 pb-3">
                                <div class="col-md-6 col-lg-6 col-12">
                                    <label class="form-label" for="name">Name</label>
                                    <input class="form-control" name="name" id="name" type="text" required="" placeholder="Enter name">
                                </div>
                                <div class="col-md-6 col-lg-6 col-12">
                                    <label class="form-label" for="initial">Initial</label>
                                    <input class="form-control" name="initial" id="initial" type="text" required="" placeholder="Enter initial">
                                </div>
                            </div>
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</x-layout>

resources/views/master/department/edit.blade.php
<div>
    <!-- An unexamined life is not worth living. - Socrates -->
</div>

resources/views/master/department/index.blade.php
<x-layout>
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Basic DataTables</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item">Data Tables</li>
                        <li class="breadcrumb-item active">Basic DataTables</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <!-- Zero Configuration  Starts-->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header pb-0">
                        <h5>Zero Configuration</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="display" id="basic-1">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Initial</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ( $departments as $department )
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $department->name }}</td>
                                        <td>{{ $department->initial }}</td>
                                        <td>
                                            <ul class="action">
                                                <li class="edit">
                                                    <a href="{{ route('department.edit', $department->id) }}"><i class="icon-pencil-alt"></i></a>
                                                </li>
                                                <li class="delete">
                                                    <form action="{{ route('department.destroy', $department->id) }}">
                                                    @csrf
                                                    <input type="hidden" name="id" value="{{ encrypt($department->id) }}">
                                                    <button style="border: 0;background: none;padding: 0;">
                                                        <i class="icon-trash"></i>
                                                    </button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Zero Configuration  Ends-->
        </div>
    </div>
    <!-- Container-fluid Ends-->
</x-layout>